server:
  port: 9000
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:3000/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: zuul #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
spring:
  application:
    name: zuul #此实例注册到eureka服务端的name
  main:
    allow-bean-definition-overriding: true

zuul:
  # 路由配置
  prefix: /api   # 增加域名前缀
  routes: # 下面是自定义配置
    ignored-services: server-power # 禁用微服务名称访问，"*" 是禁用所有微服务
    stripPrefix: false  # 是否清掉路径中的/api
    user: # 项目别名
      serviceId: user  # 微服务名称
      path: /u1/**   # 设置别名路径
    power:
      serviceId: power
      path: /p1/**

